name: 'run'

on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.11

      - name: requirements
        run : pip3 install -r requirements.txt

      - name: main
        env:
          cookie_javbus: ${{ secrets.cookie_javbus }}
        run: |
          python3 ../javbus/javbus.py

      - name: 删除运行记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 3
